chore: migrate nose to pytest
alecthomas/flask_injector pull request #72
Opened 2022-03-07 17:01 UTC by zhangcheng

Since nose is too outdated to support Python 3.10
```
  File "/Users/czhang/workspace/vendor/flask_injector/ve3.10/lib/python3.10/site-packages/nose/suite.py", line 106, in _set_tests
    if isinstance(tests, collections.Callable) and not is_suite:
AttributeError: module 'collections' has no attribute 'Callable'
```

2022-06-01 13:33 UTC, jstasiak commented on Makefile
> +	coverage run --source=$(SOURCES) -m pytest -v $(SOURCES)/tests.py && coverage report -m
The `$(SOURCES/tests.py` part depends on `$SOURCES` being set to a very specific value – namely just `flask_injector`. I'm not happy with depending on that so I propose to use just `pytest -v $(SOURCES)`

2022-06-01 13:34 UTC, jstasiak requested changes
Hey! Thank you very much for this, there are a few small changes to make but LGTM otherwise

2022-06-01 13:34 UTC, jstasiak commented on requirements-dev.txt
> +coverage
```suggestion
```

#70 handles this

2022-06-01 13:34 UTC, jstasiak commented on .gitignore
> +ve*/
Please remove the additions to `.gitignore`, they aren't related to this PR

2022-06-02 05:29 UTC, zhangcheng commented
> Hey! Thank you very much for this, there are a few small changes to make but LGTM otherwise

Got it @jstasiak , will take care of them in a while. :-)

2022-06-14 23:36 UTC, jstasiak commented
Thank you for the contribution, merged as #73 with some changes

2022-06-14 23:36 UTC, closed without merging